import {Component, OnDestroy, OnInit} from '@angular/core';

import {
  faUsers,
  faFrown,
} from '@fortawesome/pro-solid-svg-icons';


import {
  NbMediaBreakpoint,
  NbMediaBreakpointsService
} from "../../../sharebook-nebular/theme/services/breakpoints.service";
import {NbThemeService} from "../../../sharebook-nebular/theme/services/theme.service";

export interface IQuote {
  name: string;
  text: string;

  one: string;
  two: string;
  three: string;
}

@Component({
  selector: 'app-chess-stuff',
  templateUrl: './chess-stuff.component.html',
  styleUrls: ['./chess-stuff.component.scss']
})
export class ChessStuffComponent implements OnInit, OnDestroy {

  constructor(private themeService: NbThemeService,
              private breakpointService: NbMediaBreakpointsService) {

    this.breakpoints = this.breakpointService.getBreakpointsMap();
    this.themeSubscription = this.themeService.onMediaQueryChange()
      .subscribe(([oldValue, newValue]) => {
        this.breakpoint = newValue;
      });
  }

  ngOnInit(): void {
    this.initializeQuotes();
  }

  ngOnDestroy() {
    this.themeSubscription.unsubscribe();
  }

  faUsers = faUsers;
  faFrown = faFrown;

  breakpoint: NbMediaBreakpoint;
  breakpoints: any;
  themeSubscription: any;


  quotes: IQuote[];

  private initializeQuotes() {
    this.quotes = [
      {
        name: 'Magnus Carlsen',
        text: 'Some people think that if their opponent plays a beautiful game, it’s OK to lose. I don’t. You have to be merciless.',
        one: 'heading',
        two: 'heading',
        three: 'text',
      },
      {
        name: 'Irving Chernev',
        text: 'Every chess master was once a beginner.',
        one: 'basic',
        two: 'body',
        three: 'basic',
      },
      {
        name: 'Vladimir Kramnik',
        text: 'If something defines his character, then it will also define his way of playing.',
        one: 'hint',
        two: 'hint',
        three: 'hint',
      },
      {
        name: 'Bill Hartston',
        text: 'Chess doesn’t drive people mad, it keeps mad people sane.',
        one: 'link',
        two: 'link',
        three: 'link',
      },
      {
        name: 'Bobby Fischer',
        text: 'I don’t believe in psychology. I believe in good moves.',
        one: 'primary',
        two: 'status-primary',
        three: 'primary',
      },
      {
        name: 'François-André Danican Philidor',
        text: 'Pawns are the soul of the game.',
        one: 'success',
        two: 'status-success',
        three: 'success',
      },
      {
        name: 'Nigel Short',
        text: 'Modern chess is too much concerned with things like pawn structure. Forget it, checkmate ends the game.',
        one: 'info',
        two: 'status-info',
        three: 'info',
      },
      {
        name: 'Aron Nimzowitsch',
        text: 'The passed pawn is a criminal, who should be kept under lock and key. Mild measures, such as police surveillance, are not sufficient.',
        one: 'warning',
        two: 'status-warning',
        three: 'warning',
      },
      {
        name: 'Albert Einstein',
        text: 'Chess holds its master in its own bonds, shackling the mind and brain so that the inner freedom of the very strongest must suffer.',
        one: 'danger',
        two: 'status-danger',
        three: 'danger',
      },
      {
        name: 'José Raúl Capablanca',
        text: 'You may learn much more from a game you lose than from a game you win. You will have to lose hundreds of games before becoming a good player.',
        one: 'heading',
        two: 'heading',
        three: 'text',
      },
      {
        name: 'Savielly Tartakower',
        text: 'Tactics is knowing what to do when there is something to do; strategy is knowing what to do when there is nothing to do.',
        one: 'basic',
        two: 'body',
        three: 'basic',
      },
      {
        name: 'Mikhail Chigorin',
        text: 'Even a poor plan is better than no plan at all.',
        one: 'hint',
        two: 'hint',
        three: 'hint',
      },
      {
        name: 'Cecil Purdy',
        text: 'Pawn endings are to chess what putting is to golf.',
        one: 'link',
        two: 'link',
        three: 'link',
      },
      {
        name: 'Savielly Tartakower',
        text: 'Nobody ever won a chess game by resigning.',
        one: 'primary',
        two: 'status-primary',
        three: 'primary',
      },
      {
        name: 'Hans Ree',
        text: 'Chess is beautiful enough to waste your life for.',
        one: 'success',
        two: 'status-success',
        three: 'success',
      },
      {
        name: 'Nigel Short',
        text: 'If your opponent offers you a draw, try to work out why he thinks he’s worse off.',
        one: 'info',
        two: 'status-info',
        three: 'info',
      },
      {
        name: 'Savielly Tartakower',
        text: 'The blunders are all there on the board, waiting to be made.',
        one: 'warning',
        two: 'status-warning',
        three: 'warning',
      },
      {
        name: 'Mikhail Tal',
        text: 'There are two types of sacrifices: correct ones, and mine.',
        one: 'danger',
        two: 'status-danger',
        three: 'danger',
      },
      {
        name: 'Mikhail Tal',
        text: 'When I asked Fischer why he had not played a certain move in our game, he replied: \'Well, you laughed when I wrote it down.\'.',
        one: 'heading',
        two: 'heading',
        three: 'text',
      },
      {
        name: 'Boris Spassky',
        text: 'We were like bishops of opposite color.',
        one: 'basic',
        two: 'body',
        three: 'basic',
      },
      {
        name: 'Emanuel Lasker',
        text: 'When you see a good move, look for a better one.',
        one: 'hint',
        two: 'hint',
        three: 'hint',
      },
      {
        name: 'Fred Reinfeld',
        text: 'The Pin is mightier than the sword.',
        one: 'link',
        two: 'link',
        three: 'link',
      },
      {
        name: 'Bobby Fischer',
        text: 'All I want to do, ever, is play chess.',
        one: 'primary',
        two: 'status-primary',
        three: 'primary',
      },
      {
        name: 'Max Euwe',
        text: 'Strategy requires thought, tactics require observation.',
        one: 'success',
        two: 'status-success',
        three: 'success',
      },
      {
        name: 'Wilhelm Steinitz',
        text: 'Only the player with the initiative has the right to attack.',
        one: 'info',
        two: 'status-info',
        three: 'info',
      },
      {
        name: 'Savielly Tartakower',
        text: 'Chess is a fairy tale of 1001 blunders.',
        one: 'warning',
        two: 'status-warning',
        three: 'warning',
      },
      {
        name: 'Bobby Fischer',
        text: 'I give 98 percent of my mental energy to chess. Others give only 2 percent.',
        one: 'danger',
        two: 'status-danger',
        three: 'danger',
      },
      {
        name: 'Bobby Fischer',
        text: 'Tactics flow from a superior position.',
        one: 'heading',
        two: 'heading',
        three: 'text',
      },
      {
        name: 'Savielly Tartakower',
        text: 'The winner of the game is the player who makes the next-to-last mistake.',
        one: 'basic',
        two: 'body',
        three: 'basic',
      },
      {
        name: 'Emanuel Lasker',
        text: 'The hardest game to win is a won game.',
        one: 'hint',
        two: 'hint',
        three: 'hint',
      },
      {
        name: 'Wilhelm Steinitz',
        text: 'A sacrifice is best refuted by accepting it.',
        one: 'link',
        two: 'link',
        three: 'link',
      },
      {
        name: 'Siegbert Tarrasch',
        text: 'Many have become chess masters; no one has become the master of chess.',
        one: 'primary',
        two: 'status-primary',
        three: 'primary',
      },
      {
        name: 'Bobby Fischer',
        text: 'Your body has to be in top condition. Your chess deteriorates as your body does. You can’t separate body from mind.',
        one: 'success',
        two: 'status-success',
        three: 'success',
      },
      {
        name: 'Chinese Proverb',
        text: 'Life is like a game of Chess, changing with each move.',
        one: 'info',
        two: 'status-info',
        three: 'info',
      },
      {
        name: 'Purdy',
        text: 'Chess is as much a mystery as women.',
        one: 'warning',
        two: 'status-warning',
        three: 'warning',
      },
      {
        name: 'Aron Nimzowitsch',
        text: 'Even the laziest king flees wildly in the face of a double check.',
        one: 'danger',
        two: 'status-danger',
        three: 'danger',
      },
      {
        name: 'Italian Proverb',
        text: 'After the game, the king and the pawn go into the same box.',
        one: 'heading',
        two: 'heading',
        three: 'text',
      },
      {
        name: 'Bobby Fischer',
        text: 'A strong memory, concentration, imagination, and a strong will is required to become a great Chess player.',
        one: 'basic',
        two: 'body',
        three: 'basic',
      },
      {
        name: 'Magnus Carlsen',
        text: 'I\'m not really into rap.',
        one: 'hint',
        two: 'hint',
        three: 'hint',
      },
      {
        name: 'Magnus Carlsen',
        text: 'It\'s nice to be financially secure. Apart from that, I really don\'t care too much about money.',
        one: 'link',
        two: 'link',
        three: 'link',
      },
      {
        name: 'Magnus Carlsen',
        text: 'I don\'t look at computers as opponents. For me it is much more interesting to beat humans.',
        one: 'primary',
        two: 'status-primary',
        three: 'primary',
      },
      {
        name: 'Paul Morphy',
        text: 'Help your pieces so they can help you.',
        one: 'success',
        two: 'status-success',
        three: 'success',
      },
      {
        name: 'Bobby Fischer',
        text: 'Best by test: 1.e4.',
        one: 'info',
        two: 'status-info',
        three: 'info',
      },
      {
        name: 'Bobby Fischer',
        text: 'Chess demands total concentration.',
        one: 'warning',
        two: 'status-warning',
        three: 'warning',
      },
      {
        name: 'Anatoly Karpov',
        text: 'Chess is everything: art, science and sport.',
        one: 'danger',
        two: 'status-danger',
        three: 'danger',
      },
      {
        name: 'David Bronstein',
        text: 'Chess is imagination',
        one: 'heading',
        two: 'heading',
        three: 'text',
      },
      {
        name: 'Magnus Carlsen',
        text: 'I get more upset at losing at other things than chess. I always get upset when I lose at Monopoly.',
        one: 'basic',
        two: 'body',
        three: 'basic',
      },
      {
        name: 'George Eliot',
        text: 'It is never too late to be what you might have been.',
        one: 'hint',
        two: 'hint',
        three: 'hint',
      },
      {
        name: 'Hikaru Nakamura',
        text: 'In poker, you want to play the weaker guys. In chess, it\'s the opposite.',
        one: 'link',
        two: 'link',
        three: 'link',
      },
      {
        name: 'Hikaru Nakamura',
        text: 'In chess, everyone\'s accepted. That\'s what\'s great about it. You can be a little bit different. You can be an oddball.',
        one: 'primary',
        two: 'status-primary',
        three: 'primary',
      },
      {
        name: 'Hikaru Nakamura',
        text: 'I like the feeling when you don\'t have much time and you have to think fast.',
        one: 'success',
        two: 'status-success',
        three: 'success',
      },
      {
        name: 'Fabiano Caruana',
        text: 'You work for a long period of time and the results don\'t really show, but at some point everything just comes together and you start to play better, or get more confidence.',
        one: 'info',
        two: 'status-info',
        three: 'info',
      },
      {
        name: 'Paul Morphy',
        text: 'The ability to play chess is the sign of a gentleman. The ability to play chess well is the sign of a wasted life.',
        one: 'warning',
        two: 'status-warning',
        three: 'warning',
      },
      {
        name: 'Garry Kasparov',
        text: 'Chess is mental torture.',
        one: 'danger',
        two: 'status-danger',
        three: 'danger',
      },
      {
        name: 'Garry Kasparov',
        text: 'Sometimes the best defence is the best defence.',
        one: 'heading',
        two: 'heading',
        three: 'text',
      },
      {
        name: 'Garry Kasparov',
        text: 'Don’t try to play the game that goes against your natural instincts.',
        one: 'basic',
        two: 'body',
        three: 'basic',
      },
      {
        name: 'Anatoly Karpov',
        text: 'Style? I have no style.',
        one: 'hint',
        two: 'hint',
        three: 'hint',
      },
      {
        name: 'Anatoly Karpov',
        text: 'To be champion requires more than simply being a strong player; one has to be a strong human being as well.',
        one: 'link',
        two: 'link',
        three: 'link',
      },
      {
        name: 'Indian Proverb',
        text: 'Chess is a sea in which a gnat may drink and an elephant may bathe.',
        one: 'primary',
        two: 'status-primary',
        three: 'primary',
      },
      {
        name: 'Mikhail Botvinnik',
        text: 'Chess is the art of analysis.',
        one: 'success',
        two: 'status-success',
        three: 'success',
      },
      {
        name: 'Isaac Asimov',
        text: 'In life, unlike chess the game continues after checkmate.',
        one: 'info',
        two: 'status-info',
        three: 'info',
      },
      {
        name: 'Garry Kasparov',
        text: 'If you wish to succeed, you must brave the risk of failure.',
        one: 'warning',
        two: 'status-warning',
        three: 'warning',
      },
      {
        name: 'Judit Polgar',
        text: 'Without work, talent is lost.',
        one: 'danger',
        two: 'status-danger',
        three: 'danger',
      },
      {
        name: 'Judit Polgar',
        text: 'Being professional means 100% is not enough. Number one, two and three in my life was chess. The reality for women is, when a child comes into the picture, priorities change.',
        one: 'heading',
        two: 'heading',
        three: 'text',
      },
      {
        name: 'Bobby Fischer',
        text: 'I like the moment when I break a man\'s ego',
        one: 'basic',
        two: 'body',
        three: 'basic',
      },
      {
        name: 'Walter Tevis',
        text: 'Chess isn\'t always competitive. Chess can also be beautiful.',
        one: 'hint',
        two: 'hint',
        three: 'hint',
      },
      {
        name: 'José Raúl Capablanca',
        text: 'A good player is always lucky.',
        one: 'link',
        two: 'link',
        three: 'link',
      },
      {
        name: 'Anand Viswanathan',
        text: 'Nowadays, when you’re not a grandmaster at 14, you can forget about it.',
        one: 'primary',
        two: 'status-primary',
        three: 'primary',
      },
      {
        name: 'Anand Viswanathan',
        text: 'For every door the computers have closed they have opened a new one.',
        one: 'success',
        two: 'status-success',
        three: 'success',
      },
      {
        name: 'Anand Viswanathan',
        text: 'I would never suggest to anyone that they drop school for chess. First of all even if you can make it in chess, your social skills need to be developed there.',
        one: 'info',
        two: 'status-info',
        three: 'info',
      },
      {
        name: 'Anand Viswanathan',
        text: 'Confidence is very important – even pretending to be confident. If you make a mistake but do not let your opponent see what you are thinking then he may overlook the mistake.',
        one: 'warning',
        two: 'status-warning',
        three: 'warning',
      },
      {
        name: 'Anand Viswanathan',
        text: 'There is always the risk of being over-confident when you are preparing to face a weaker player.',
        one: 'danger',
        two: 'status-danger',
        three: 'danger',
      },
      {
        name: 'Anand Viswanathan',
        text: 'We want more women players to take up chess. There are few participants at the national level and hope it will grow.',
        one: 'heading',
        two: 'heading',
        three: 'text',
      },
      {
        name: 'Magnus Carlsen',
        text: 'This is a problem that’s been around in chess for a long time, chess societies have not been very kind to women and girls over the years. Certainly there needs to be a bit of a change in culture.',
        one: 'basic',
        two: 'body',
        three: 'basic',
      },
      {
        name: 'Hou Yifan',
        text: 'One thing which has been very important to my success is my mental mindset. I have a relatively positive and quiet one, and while I’m not the kind of person that spends 10 hours per day studying chess, when I do study, I can be fully concentrated for 4-5 hours, and I maximize that time.',
        one: 'hint',
        two: 'hint',
        three: 'hint',
      },
      {
        name: 'Hou Yifan',
        text: 'The deeper you go, you realize there’s more things you don’t know.',
        one: 'link',
        two: 'link',
        three: 'link',
      },
      {
        name: 'Siegbert Tarrasch',
        text: 'Chess is a terrible game. If you have no center, your opponent has a freer position. If you do have a center, then you really have something to worry about!.',
        one: 'primary',
        two: 'status-primary',
        three: 'primary',
      },
      {
        name: 'Fabiano Caruana',
        text: 'Probably they are a bit frustrated that they can\'t pick a draw against me.',
        one: 'success',
        two: 'status-success',
        three: 'success',
      },
      {
        name: 'Fabiano Caruana',
        text: 'When you feel confident you just play better more freely you don\'t question yourself don\'t think too long about if you are making the right decision.',
        one: 'info',
        two: 'status-info',
        three: 'info',
      },
      {
        name: 'Levon Aronian',
        text: 'Chess960 is healthy and good for your chess. If you get into it and not just move the pieces to achieve known positions it really improves your chess vision.',
        one: 'warning',
        two: 'status-warning',
        three: 'warning',
      },
      {
        name: 'Levon Aronian',
        text: 'As a chess player one has to be able to control one\'s feelings, one has to be as cold as a machine.',
        one: 'danger',
        two: 'status-danger',
        three: 'danger',
      },
      {
        name: 'Boris Gelfand',
        text: 'The good thing in chess is that very often the best moves are the most beautiful ones. The beauty of logic.',
        one: 'heading',
        two: 'heading',
        three: 'text',
      },
      {
        name: 'Peter Leko',
        text: 'My favourite victory is when it is not even clear where my opponent made a mistake.',
        one: 'basic',
        two: 'body',
        three: 'basic',
      },
      {
        name: 'Siegbert Tarrasch',
        text: 'I have always a slight feeling of pity for the man who has no knowledge of Chess.',
        one: 'hint',
        two: 'hint',
        three: 'hint',
      },
      {
        name: 'Magnus Carlsen',
        text: 'I spend hours playing chess because I find it so much fun. The day it stops being fun is the day I give up.',
        one: 'link',
        two: 'link',
        three: 'link',
      },
      {
        name: 'Magnus Carlsen',
        text: 'Without the element of enjoyment, it is not worth trying to excel at anything.',
        one: 'primary',
        two: 'status-primary',
        three: 'primary',
      },
      {
        name: 'Judit Polgar',
        text: 'Chess demolishes differences. It\'s a language of different generations.',
        one: 'success',
        two: 'status-success',
        three: 'success',
      },
      {
        name: 'Anish Giri',
        text: 'I barely know what my plans are for tomorrow, but I hope chess will remain a major part of my life.',
        one: 'info',
        two: 'status-info',
        three: 'info',
      },
      {
        name: 'Anish Giri',
        text: 'I have tremendous respect for my colleagues.',
        one: 'warning',
        two: 'status-warning',
        three: 'warning',
      },
      {
        name: 'Anish Giri',
        text: 'I think chess players are not always what you think them to be. Or maybe it\'s our job to appear serious.',
        one: 'danger',
        two: 'status-danger',
        three: 'danger',
      },
      {
        name: 'Jan Timman',
        text: 'Carlsen\'s repertoire is aimed at avoiding an early crisis in the game. He invariably aims for middlegames that lend themselves to a strategic approach.',
        one: 'heading',
        two: 'heading',
        three: 'text',
      },
      {
        name: 'Anish Giri',
        text: 'Magnus and I are very close in terms of style, but in our approach to the game we\'re total opposites. Magnus tries to put the accent only on play, getting away from preparation, but for me preparation plays an enormous role.',
        one: 'basic',
        two: 'body',
        three: 'basic',
      },
      {
        name: 'Anand Viswanathan',
        text: 'Magnus has an incredible innate sense. ... The majority of ideas occur to him absolutely naturally. He\'s also very flexible, he knows all the structures and he can play almost any position.',
        one: 'hint',
        two: 'hint',
        three: 'hint',
      },
      {
        name: 'David Levy',
        text: 'I prefer to lose a really good game than to win a bad one.',
        one: 'link',
        two: 'link',
        three: 'link',
      },
      {
        name: 'Evan Esar',
        text: 'Age brings wisdom to some men, and to others chess.',
        one: 'primary',
        two: 'status-primary',
        three: 'primary',
      },
      {
        name: 'French Proverb',
        text: 'You cannot play at chess if you are kind-hearted.',
        one: 'success',
        two: 'status-success',
        three: 'success',
      },
      {
        name: 'Stephan Gerzadowicz',
        text: 'Openings teach you openings. Endgames teach you chess!',
        one: 'info',
        two: 'status-info',
        three: 'info',
      },
      {
        name: 'Byron',
        text: 'Life is too short for chess.',
        one: 'warning',
        two: 'status-warning',
        three: 'warning',
      },
      {
        name: 'Vasily Smyslov',
        text: 'In chess, as in life, a man is his own most dangerous opponent.',
        one: 'danger',
        two: 'status-danger',
        three: 'danger',
      },
      {
        name: 'Marcel Duchamp',
        text: 'I have come to the personal conclusion that while all artists are not chess players, all chess players are artists.',
        one: 'heading',
        two: 'heading',
        three: 'text',
      },
      {
        name: 'Paul Morphy',
        text: 'Unlike other games in which lucre is the end and aim, [chess] recommends itself to the wise by the fact that its mimic battles are fought for no prize but honor. It is eminently and emphatically the philosopher’s game.',
        one: 'basic',
        two: 'body',
        three: 'basic',
      },
      {
        name: 'Johannes Zukertort',
        text: 'Chess is the struggle against the error.',
        one: 'hint',
        two: 'hint',
        three: 'hint',
      },
      {
        name: 'Ralph Charell',
        text: 'Avoid the crowd. Do your own thinking independently. Be the chess player, not the chess piece.',
        one: 'link',
        two: 'link',
        three: 'link',
      },
      {
        name: 'Blaise Pascal',
        text: 'Chess is the gymnasium of the mind.',
        one: 'primary',
        two: 'status-primary',
        three: 'primary',
      },
      {
        name: 'Hein Donner',
        text: 'Give me a difficult positional game, I will play it. But totally won positions, I cannot stand them.',
        one: 'success',
        two: 'status-success',
        three: 'success',
      },
      {
        name: 'Garry Kasparov',
        text: 'I used to attack because it was the only thing I knew. Now I attack because I know it works best.',
        one: 'info',
        two: 'status-info',
        three: 'info',
      },
      {
        name: 'Rudolph Spielmann',
        text: 'Play the opening like a book, the middlegame like a magician, and the endgame like a machine.',
        one: 'warning',
        two: 'status-warning',
        three: 'warning',
      },
      {
        name: 'H. G. Wells',
        text: 'There is no remorse like the remorse of chess.',
        one: 'danger',
        two: 'status-danger',
        three: 'danger',
      },
      {
        name: 'William Napier',
        text: 'Of chess, it has been said that life is not long enough for it, but that is the fault of life, not chess',
        one: 'heading',
        two: 'heading',
        three: 'text',
      },
      {
        name: 'Lodewijk Prins',
        text: 'The only thing chess players have in common is chess',
        one: 'basic',
        two: 'body',
        three: 'basic',
      },
      {
        name: 'Bernhard Horwitz',
        text: 'One bad move nullifies forty good ones.',
        one: 'hint',
        two: 'hint',
        three: 'hint',
      },
      {
        name: 'Alfred Binet',
        text: 'Could we look into the head of a Chess player,we should see there a whole world of feelings, images, ideas, emotion and passion.',
        one: 'link',
        two: 'link',
        three: 'link',
      },
      {
        name: 'Max Euwe',
        text: 'Alekhine is a poet who creates a work of art out of something that would hardly inspire another man to send home a picture post card.',
        one: 'primary',
        two: 'status-primary',
        three: 'primary',
      },
      {
        name: 'Jose Raul Capablanca',
        text: 'Chess books should be used as we use glasses: to assist the sight, although some players make use of them as if they thought they conferred sight.',
        one: 'success',
        two: 'status-success',
        three: 'success',
      },
      {
        name: 'Emanuel Lasker',
        text: 'The combination player thinks forward; he starts from the given position, and tries the forceful moves in his mind.',
        one: 'info',
        two: 'status-info',
        three: 'info',
      },
      {
        name: 'Savielly Tartakower',
        text: 'A Chess game is divided into three stages: the first, when you hope you have the advantage, the second when you believe you have an advantage, and the third… when you know you’re going to lose!',
        one: 'warning',
        two: 'status-warning',
        three: 'warning',
      },
      {
        name: 'Judith Polgar',
        text: 'Chess is thirty to forty percent psychology. You don’t have this when you play a computer. I can’t confuse it.',
        one: 'danger',
        two: 'status-danger',
        three: 'danger',
      },
      {
        name: 'Marcel Duchamp',
        text: 'I am still a victim of Chess. It has all the beauty of art and much more. It cannot be commercialized. Chess is much purer than art in its social position.',
        one: 'heading',
        two: 'heading',
        three: 'text',
      },
      {
        name: 'Alexander Alekhine',
        text: 'When asked, -How is that you pick better moves than your opponents? I responded: I’m very glad you asked me that, because, as it happens, there is a very simple answer. I think up my own moves, and I make my opponent think up his.',
        one: 'basic',
        two: 'body',
        three: 'basic',
      },
      {
        name: 'Aaron Nimzovich',
        text: 'The beauty of a move lies not in its’ appearance but in the thought behind it.',
        one: 'hint',
        two: 'hint',
        three: 'hint',
      },
      {
        name: 'Paul Morphy',
        text: 'Checkers is for tramps.',
        one: 'link',
        two: 'link',
        three: 'link',
      },
      {
        name: 'Gary Kasparov',
        text: 'We like to think.',
        one: 'primary',
        two: 'status-primary',
        three: 'primary',
      },
      {
        name: 'Bobby Fischer',
        text: 'That\'s what Chess is all about. One day you give your opponent a lesson, the next day he gives you one.',
        one: 'success',
        two: 'status-success',
        three: 'success',
      },
      {
        name: 'Irving Chernev',
        text: 'If once a man delays castling and his king remains in the center, files will open up against him, bishops sweep the board, rooks will dominate the seventh rank, and pawns turn into queens.',
        one: 'info',
        two: 'status-info',
        three: 'info',
      },
      {
        name: 'Emanuel Lasker',
        text: 'The laws of chess do not permit a free choice: you have to move whether you like it or not.',
        one: 'warning',
        two: 'status-warning',
        three: 'warning',
      },
      {
        name: 'Boris Spassky',
        text: 'The power of hanging Pawns is based precisely in their Mobility, in their Ability to create acute situations instantly.',
        one: 'danger',
        two: 'status-danger',
        three: 'danger',
      },
      {
        name: 'Bobby Fischer',
        text: 'Chess is a matter of delicate judgement, knowing when to punch and how to duck.',
        one: 'heading',
        two: 'heading',
        three: 'text',
      },
      {
        name: 'Emanuel Lasker',
        text: 'Without error there can be no brilliancy.',
        one: 'basic',
        two: 'body',
        three: 'basic',
      },
      {
        name: 'Mikhail Tal',
        text: 'You must take your opponent into a deep dark forest where 2+2=5, and the path leading out is only wide enough for one.',
        one: 'hint',
        two: 'hint',
        three: 'hint',
      },
      {
        name: 'Akiba Rubinstein',
        text: 'Who is your opponent tonight, tonight I am playing against the Black pieces.',
        one: 'link',
        two: 'link',
        three: 'link',
      },
      {
        name: 'Savielly Tartakower',
        text: 'The tactician must know what to do whenever something needs doing; the strategist must know what to do when nothing needs doing.',
        one: 'primary',
        two: 'status-primary',
        three: 'primary',
      },
      {
        name: 'Jose Raul Capablanca',
        text: 'In order to improve your game you must study the endgame before everything else; for, whereas the endings can be studied and mastered by themselves, the middlegame and the opening must be studied in relation to the endgame.',
        one: 'success',
        two: 'status-success',
        three: 'success',
      },
      {
        name: 'Susan Polgar',
        text: 'Win with grace, lose with dignity!',
        one: 'info',
        two: 'status-info',
        three: 'info',
      },
      {
        name: 'Bobby Fischer',
        text: 'Psychologically, you have to have confidence in yourself and this confidence should be based on fact.',
        one: 'warning',
        two: 'status-warning',
        three: 'warning',
      },
      {
        name: 'Viktor Korchnoi',
        text: 'As a rule, the more mistakes there are in a game, the more memorable it remains, because you have suffered and worried over each mistake at the board.',
        one: 'danger',
        two: 'status-danger',
        three: 'danger',
      },
      {
        name: 'Alexander Alekhine',
        text: 'Chess first of all teaches you to be objective.',
        one: 'heading',
        two: 'heading',
        three: 'text',
      },
      {
        name: 'Francois-Andre Danican Philidor',
        text: 'A pawn, when separated from his fellows, will seldom or never make a fortune.',
        one: 'basic',
        two: 'body',
        three: 'basic',
      },
      {
        name: 'Viktor Korchnoi',
        text: 'Those who think that it is easy to play chess are mistaken. During a game a player lives on his nerves, and at the same time he must be perfectly composed.',
        one: 'hint',
        two: 'hint',
        three: 'hint',
      },
      {
        name: 'XXXXXX',
        text: 'YYYYYY.',
        one: 'link',
        two: 'link',
        three: 'link',
      },
      {
        name: 'Jeremy Silman',
        text: 'If your opponent cannot do anything active, then don\'t rush the position; instead you should let him sit there, suffer, and beg you for a draw.',
        one: 'primary',
        two: 'status-primary',
        three: 'primary',
      },
      {
        name: 'Savielly Tartakower',
        text: 'Some part of a mistake is always correct.',
        one: 'success',
        two: 'status-success',
        three: 'success',
      },
      {
        name: 'David Bronstein',
        text: 'To lose one\'s objective attitude to a position, nearly always means ruining your game.',
        one: 'info',
        two: 'status-info',
        three: 'info',
      },
      {
        name: 'Joseph Henry Blackburne',
        text: 'My opponent left a glass of whisky \'en prise\' and I took it \'en passant\'.',
        one: 'warning',
        two: 'status-warning',
        three: 'warning',
      },
      {
        name: 'Aristotle',
        text: 'When you are lonely, when you feel yourself an alien in the world, play Chess. This will raise your spirits and be your counselor in war.',
        one: 'danger',
        two: 'status-danger',
        three: 'danger',
      },
      {
        name: 'John Maynard Keynes',
        text: 'Chess is a cure for headaches.',
        one: 'heading',
        two: 'heading',
        three: 'text',
      },
      {
        name: 'Garry Kasparov',
        text: 'Any experienced player knows how a change in the character of the play influences your psychological mood',
        one: 'basic',
        two: 'body',
        three: 'basic',
      },
      {
        name: 'Rudolf Spielmann',
        text: 'We cannot resist the fascination of sacrifice, since a passion for sacrifices is part of a Chessplayer\'s nature.',
        one: 'hint',
        two: 'hint',
        three: 'hint',
      },
      {
        name: 'Samuel Reshevsky',
        text: 'My style is somewhere between that of Tal and Petrosian.',
        one: 'link',
        two: 'link',
        three: 'link',
      },
      {
        name: 'Aron Nimzowitsch',
        text: 'The isolated Pawn casts gloom over the entire chessboard.',
        one: 'primary',
        two: 'status-primary',
        three: 'primary',
      },
      {
        name: 'Gerard Schwarz',
        text: 'If you don\'t know what to do, find your worst Piece and look for a better Square.',
        one: 'success',
        two: 'status-success',
        three: 'success',
      },
      {
        name: 'Jose Raul Capablanca',
        text: 'People who want to improve should take their defeats as lessons, and endeavor to learn what to avoid in the future. You must also have the courage of your convictions. If you think your move is good, make it.',
        one: 'info',
        two: 'status-info',
        three: 'info',
      },
      {
        name: 'Jose Raul Capablanca',
        text: 'There was a time in my life when I almost thought I could never lose a single duel of chess.',
        one: 'warning',
        two: 'status-warning',
        three: 'warning',
      },
      {
        name: 'Mikhail Botvinnik',
        text: 'Chess is the art which expresses the science of logic.',
        one: 'danger',
        two: 'status-danger',
        three: 'danger',
      },
      {
        name: 'Alexander Kotov',
        text: 'Bobby Fischer is the greatest Chess genius of all time!',
        one: 'heading',
        two: 'heading',
        three: 'text',
      },
      {
        name: 'Vladimir Kramnik',
        text: 'Chess is like body-building. If you train every day, you stay in top shape. It is the same with your brain - chess is a matter of daily training.',
        one: 'basic',
        two: 'body',
        three: 'basic',
      },
      {
        name: 'Emo Philips',
        text: 'A computer once beat me at chess, but it was no match for me at kick boxing.',
        one: 'hint',
        two: 'hint',
        three: 'hint',
      },
      {
        name: 'Vlastimil Hort',
        text: 'In blitz, the Knight is stronger than the Bishop.',
        one: 'link',
        two: 'link',
        three: 'link',
      },
      {
        name: 'Boris Spassky',
        text: 'I also follow chess on the Internet, where Kasparov\'s site is very interesting.',
        one: 'primary',
        two: 'status-primary',
        three: 'primary',
      },
      {
        name: 'Boris Spassky',
        text: 'I try to help developing junior chess. When I lived in USSR, I got a lot of free help from very good coaches - now I am trying to repay that debt.',
        one: 'success',
        two: 'status-success',
        three: 'success',
      },
      {
        name: 'Garry Kasparov',
        text: 'Setbacks and losses are both inevitable and essential if you\'re going to improve and become a good, even great, competitor. The art is in avoiding catastrophic losses in the key battles.',
        one: 'info',
        two: 'status-info',
        three: 'info',
      },
      {
        name: 'Savielly Tartakower',
        text: 'All Chess players should have a hobby.',
        one: 'warning',
        two: 'status-warning',
        three: 'warning',
      },
      {
        name: 'Bent Larsen',
        text: 'Lack of patience is probably the most common reason for losing a game, or drawing games that should have been won.',
        one: 'danger',
        two: 'status-danger',
        three: 'danger',
      },
      {
        name: 'Miguel Najdorf',
        text: 'Bobby just drops the pieces and they fall on the right squares.',
        one: 'heading',
        two: 'heading',
        three: 'text',
      },
      {
        name: 'Irving Chernev',
        text: 'Every chess master was once a beginner.',
        one: 'basic',
        two: 'body',
        three: 'basic',
      },
      {
        name: 'Viswanathan Anand',
        text: 'Chess is like a language, the top players are very fluent at it. Talent can be developed scientifically but you have to find first what you are good at.',
        one: 'hint',
        two: 'hint',
        three: 'hint',
      },
      {
        name: 'Mikhail Botvinnik',
        text: 'Chess is a part of culture and if a culture is declining then Chess too will decline.',
        one: 'link',
        two: 'link',
        three: 'link',
      },
      {
        name: 'Anatoly Karpov',
        text: 'Like dogs who sniff each other when meeting, chess players have a ritual at first acquaintance: they sit down to play speed chess.',
        one: 'primary',
        two: 'status-primary',
        three: 'primary',
      },
      {
        name: 'Bobby Fischer',
        text: 'You can only get good at Chess if you love the game.',
        one: 'success',
        two: 'status-success',
        three: 'success',
      },
      {
        name: 'David Bronstein',
        text: 'In chess, as in life, opportunity strikes but once.',
        one: 'info',
        two: 'status-info',
        three: 'info',
      },
      {
        name: 'David Bronstein',
        text: 'The most powerful weapon in Chess is to have the next move.',
        one: 'warning',
        two: 'status-warning',
        three: 'warning',
      },
      {
        name: 'Wilhelm Steinitz',
        text: 'I have never in my life played the French Defence, which is the dullest of all openings.',
        one: 'danger',
        two: 'status-danger',
        three: 'danger',
      },
      {
        name: 'Emanuel Lasker',
        text: 'To refer to the oft mooted question, "Which piece is stronger, the Bishop or the Knight?" it is clear that the value of the Bishop undergoes greater changes than that of the Knight.',
        one: 'heading',
        two: 'heading',
        three: 'text',
      },
      {
        name: 'Yasser Seirawan',
        text: 'Let the perfectionist play postal.',
        one: 'basic',
        two: 'body',
        three: 'basic',
      },
      {
        name: 'Garry Kasparov',
        text: 'For me, chess is a language, and if it\'s not my native tongue, it is one I learned via the immersion method at a young age.',
        one: 'hint',
        two: 'hint',
        three: 'hint',
      },
      {
        name: 'Max Euwe',
        text: 'Whoever sees no other aim in the game than that of giving checkmate to one\'s opponent will never become a good Chess player.',
        one: 'link',
        two: 'link',
        three: 'link',
      },
      {
        name: 'Alexander Alekhine',
        text: 'Chess is not only knowledge and logic.',
        one: 'primary',
        two: 'status-primary',
        three: 'primary',
      },
      {
        name: 'Jose Raul Capablanca',
        text: 'Morphy gained most of his wins by playing directly and simply, and it is simple and logical method that constitutes the true brilliance of his play, if it is considered from the viewpoint of the great masters.',
        one: 'success',
        two: 'status-success',
        three: 'success',
      },
      {
        name: 'Garry Kasparov',
        text: 'Ultimately, what separates a Winner from a Loser at the Grandmaster level is the Willingness to do the Unthinkable.',
        one: 'info',
        two: 'status-info',
        three: 'info',
      },
      {
        name: 'Alexei Shirov',
        text: 'The fact that the 7 hours time control allows us to play a great deep game is not of great importance for mass-media.',
        one: 'warning',
        two: 'status-warning',
        three: 'warning',
      },
      {
        name: 'Bobby Fischer',
        text: 'The turning point in my career came with the realization that Black should play to win instead of just steering for equality.',
        one: 'danger',
        two: 'status-danger',
        three: 'danger',
      },
      {
        name: ' Wilhelm Steinitz',
        text: 'Chess is so inspiring that I do not believe a good player is capable of having an evil thought during the game.',
        one: 'heading',
        two: 'heading',
        three: 'text',
      },
      {
        name: 'Irving Chernev',
        text: 'Every chess master was once a beginner.',
        one: 'basic',
        two: 'body',
        three: 'basic',
      },
      {
        name: 'Kiril Georgiev',
        text: 'I believe that every world champion has a greatness of his own.',
        one: 'hint',
        two: 'hint',
        three: 'hint',
      },
      {
        name: 'Alexander Grischuk',
        text: 'I think that ratings don’t lie, so I guess blitz is my worst time control now. Still the most enjoyable though.',
        one: 'link',
        two: 'link',
        three: 'link',
      },
      {
        name: 'Alexander Grischuk',
        text: 'You know, I always try not to watch Svidler during the tournament, because he is too brilliant for me and I start to feel miserable.',
        one: 'primary',
        two: 'status-primary',
        three: 'primary',
      },
      {
        name: 'Alexander Grischuk',
        text: 'Grischuk on his infamous time trouble: Procrastination is definitely the main factor.',
        one: 'success',
        two: 'status-success',
        three: 'success',
      },
      {
        name: 'Simon Williams',
        text: 'The beauty of chess is it can be whatever you want it to be. It transcends language, age, race, religion, politics, gender and socioeconomic background. Whatever your circumstances, anyone can enjoy a good fight to the death over the chess board.',
        one: 'info',
        two: 'status-info',
        three: 'info',
      },
      {
        name: 'Veselin Topalov',
        text: 'You need to believe in yourself, and everything will be okay!',
        one: 'warning',
        two: 'status-warning',
        three: 'warning',
      },
      {
        name: 'Veselin Topalov',
        text: 'I think whoever’s going to beat a champion like Carlsen will inevitably be younger than he is. For now I don’t know who that will be.',
        one: 'danger',
        two: 'status-danger',
        three: 'danger',
      },
      // {
      //   name: 'Magnus Carlsen',
      //   text: 'Some people think that if their opponent plays a beautiful game, it’s OK to lose. I don’t. You have to be merciless.',
      //   one: 'heading',
      //   two: 'heading',
      //   three: 'text',
      // },
      // {
      //   name: 'Irving Chernev',
      //   text: 'Every chess master was once a beginner.',
      //   one: 'basic',
      //   two: 'body',
      //   three: 'basic',
      // },
      // {
      //   name: 'XXXXXX',
      //   text: 'YYYYYY.',
      //   one: 'hint',
      //   two: 'hint',
      //   three: 'hint',
      // },
      // {
      //   name: 'XXXXXX',
      //   text: 'YYYYYY.',
      //   one: 'link',
      //   two: 'link',
      //   three: 'link',
      // },
      // {
      //   name: 'XXXXXX',
      //   text: 'YYYYYY.',
      //   one: 'primary',
      //   two: 'status-primary',
      //   three: 'primary',
      // },
      // {
      //   name: 'XXXXXX',
      //   text: 'YYYYYY.',
      //   one: 'success',
      //   two: 'status-success',
      //   three: 'success',
      // },
      // {
      //   name: 'XXXXXX',
      //   text: 'YYYYYY.',
      //   one: 'info',
      //   two: 'status-info',
      //   three: 'info',
      // },
      // {
      //   name: 'XXXXXX',
      //   text: 'YYYYYY.',
      //   one: 'warning',
      //   two: 'status-warning',
      //   three: 'warning',
      // },
      // {
      //   name: 'XXXXXX',
      //   text: 'YYYYYY.',
      //   one: 'danger',
      //   two: 'status-danger',
      //   three: 'danger',
      // },
    ];

    this.quotes = this.quotes.sort(() => Math.random() - 0.5);
  }

  personalityImg = 'assets/images/the-queens-gambit.jpg';

  onNavigate() {
    window.open("https://www.chesspersonality.com/", "_blank");
  }

}
