version: '3.4'

services:
  webspa:
    image: webspa:dev
    container_name: WebSPA
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "WebSPA"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_webspa$
    volumes:
      - C:\Users\volen\OneDrive\Desktop\WorldFeed\WorldFeed\Server\src\Web\WebSPA:/app
      - C:\Users\volen\OneDrive\Desktop\WorldFeed\WorldFeed\Server\src:/src
      - C:\Users\volen\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_webspa$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_webspa$ \"/src/../../../../eShopOnContainers1/eShopOnContainers/src/Web/WebSPA/bin/Debug/netcoreapp3.1/WebSPA.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true