blank_issues_enabled: false
contact_links:
  - name: 💬 IRC
    url: https://kiwiirc.com/client/irc.freenode.net/#sharebook
    about: Chat with us via IRC for quick Q/A here
  - name: 💬 Matrix
    url: https://matrix.to/#/#sharebook:matrix.org
    about: Chat with us via Matrix for quick Q/A here
  - name: 🤷💻🤦 Forum
    url: https://framacolibri.org/c/sharebook
    about: You can ask and answer other questions here
