var TEXT_PRELOADER_CONTINUE = "START";
var TEXT_GAMEOVER = "GAME OVER";
var TEXT_SCORE = "SCORE";
var TEXT_BEST_SCORE = "BEST SCORE";
var TEXT_HELP1_PC = "Use arrow keys to drive your starship. Cross the screen from side to side to avoid blocks";
var TEXT_HELP1_MOBILE = "TOUCH THE LEFT OR RIGHT SIDE TO MOVE THE STARSHIP. Cross the screen from side to side to avoid blocks";
var TEXT_PAUSE = "PAUSE";
var TEXT_ARE_SURE = "ARE YOU SURE?";
var TEXT_DEVELOPED = "DEVELOPED BY";
var TEXT_MOVE = "MOVE";
var TEXT_EAT = "EAT";
var TEXT_AVOID = "AVOID";

var TEXT_SHARE_IMAGE = "200x200.jpg";
var TEXT_SHARE_TITLE = "Congratulations!";
var TEXT_SHARE_MSG1 = "You collected <strong>";
var TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
var TEXT_SHARE_SHARE1 = "My score is ";
var TEXT_SHARE_SHARE2 = " points! Can you do better?";