import {Injectable} from "@angular/core";

@Injectable()
export class FactsService {
  private facts: string[] = [
    'Ra6!! bxa6 b7#',
    'Nf7+ Kg8 Nh6+ Kh8 Qg8+!! Rxg8 Nf7#',
    'Qh4#',
    'Qxc6+!! bxc6 Ba6#',
    'Nd6#',
    'Ne2+ Kh1 Qxh2+!! Kxh2 Rh6#',
    'Qd8+!! Kxd8 Bg5+ Kc7 (Ke8 Rd8#) Bd8#',
    'Glaciers and ice sheets hold about 69 percent of the world\'s freshwater',
    'The fastest gust of wind ever recorded on Earth was 253 miles per hour',
    'The best place in the world to see rainbows is in Hawaii 🌈',
    'The longest place name on the planet is 85 letters long',
    'Niagara Falls never freezes',
    'Egypt is classified as the oldest country in the world',
    'Tim Berners-Lee created the first ever web browser (World Wide Web), in 1990',
    'Psychological fact - When a person cries and the first tear falls from the right eye, it\'s from happiness. But when the first tear is from the left eye, it\'s from pain',
    'When you do a Google query, 1000 machines are used to find the answer in 0.2 seconds.',
    'Owls don’t have eyeballs 🦉',
    'Samsung tests phone durability with a butt-shaped robot 🤖',
    'There were active volcanoes on the moon when dinosaurs were alive 🐱‍🐉',
    'You only have two body parts that never stop growing node 👃🏼 and ears 👂🏼',
    'Europeans were scared of eating tomatoes when they were first introduced 🍅',
    'The Eiffel Tower can grow more than six inches during the summer 🗼',
    'The longest chess game ever was I.Nikolic - Arsovic, Belgrade 1989, which ended in 269 moves. The game was a draw',
    'According to the America\'s Foundation for Chess, there are 169,518,829,100 ,544,000,000,00 0,000,000 (approximately 1.70x10 29) ways to play the first 10 moves of a game of chess',
    'The longest chess game theoretically possible is 5,949 moves.',
    'The number of possibilities of a Knight’s tour is over 122 million 🐴',
    'There were 72 consecutive Queen moves in the Mason-Mackenzie game at London in 1882',
    'The second book ever printed in the English language was about chess!! 🙀',
    'More human twins are being born now than ever before',
    'The world wastes about 1 billion metric tons of food each year. This is just terrible..',
    'The world\'s smallest reptile was first reported in 2021 - Brookesia nana',
    'The moon has moonquakes 🌑',
    'Cotton candy was invented by a dentist William Morrison',
    'Chewing gum boosts blood flow to your brain, which may help improve your memory 🧠',
    'Bees sometimes sting other bees 🐝',
    'One man has saved more than 200 people from suicide - Officer Kevin Briggs',
    'Dinosaurs lived on every continent. The continents were arranged together as a single supercontinent called Pangea',
    'Some planets produce diamond rain 💎',
    'Saudi Arabia imports camels from Australia 🐫',
    'Humans have been performing dentistry since 7000BC, which makes dentists one of the oldest professions 🦷',
    'Canada eats more macaroni and cheese than any other nation in the world 🍁',
    'Snakes can help predict earthquakes. They can sense a coming earthquake from 75 miles away, up to five days before it happens 🐍',
    'Dinosaurs would swallow large rocks which stayed in their stomach to help churn and digest food 🐱‍🐉',
    'It snowed in the Sahara desert for 30 minutes on February 18, 1979 🌨',
    'Astronauts actually get taller when in space 👩🏼‍🚀',
    'In California, you can get a ticket if you’re driving too slow 🚗',
    'A snail can sleep for 3 years 🐌',
    'A group of horses will not go to sleep at the same time – at least one of them will stay awake to look out for the others 🐴',
    'Jellyfish are considered biologically immortal. They don’t age and will never die unless they are killed',
    'Crows can remember the faces of individual humans. They can also hold a grudge',
    'There are more stars in space than there are grains of sand on every beach in the world ✨',
    'Selfies now cause more deaths than shark attacks 🦈🤳🏼',
    'All the electricity powering the internet weighs the same as an apricot',
    'The average person produces 14 to 23 farts every day, and each fart travels from your body at 7 mph 💨',
    'The shark is the only fish that can blink with both eyes 🦈',
    'An ostrich’s eye is bigger than its whole brain',
    'The Moon is drifting away from the Earth 🌚',
    'There is water on the Moon! 🧊',
    'Jupiter\'s moon Io has towering volcanic eruptions 🌋',
    'Mars has the longest valley in the Solar System - Valles Marineris',
    'Pluto has a bizarre atmosphere - scientists saw the haze extending as high as 1,000 miles (1,600 km), rising higher above the surface than the atmosphere on Earth',
    'A grizzly bear\'s bite is strong enough to crush a bowling ball 🐻',
    'The human brain takes in 11 million bits of information every second but is aware of only 40 🧠',
    'Sudan has the most pyramids in the world (not Egypt)',
    'The Sahara Desert used to be a tropical rainforest',
    'Snow is not white but rather translucent ❄',
    'The Sun’s mass takes up 99.86% of the Solar System ☀',
    '1.3 million Earths can fit inside the Sun',
    'One day on Venus is longer than one year',
    'There is a planet made of diamonds 💎',
    'Space is completely silent 🔈',
    'The word "checkmate" comes from the Arabic word "shah mat" which translates to "The king is dead" in English',
    'The new move where the pawn could move two steps instead of one was introduced in Spain in 1280 ♟',
    'Chess is also called the "Game of Kings" since for a very long time in the past, it was just played by the Nobel and Kings',
    'The shortest number of moves to achieve checkmate is just two moves! One sequence is called "Fool’s mate runs" Thus, 1.f3 e5 and 2.g4 Qh4 checkmate',
    'NASA says that there are zillions of uncountable stars. A zillion is any uncountable amount ✨',
    'The Apollo astronauts\' footprints on the moon will probably stay there for at least 100 million years\n 👣',
    'Jupiter\'s Great Red Spot is shrinking',
    'The current version of castling in chess was established in France in 1620 and in England in 1640',
    'The longest Chess problem, mate in 290 moves, is a credit to Blathy, Otto',
    'The longest title holder of the World chess championship is Doctor Emanuel Lasker. He held this title longer than any other player in the history for 26 years and 337 days',
    'The youngest World chess champion ever was the Soviet player named as Garry Kasparov who was of 22 years in 1985',
    'Emanuel Lasker, who was the World Chess Champion, was a good friend of Albert Einstein',
    'Magnus Carlsen surpassed a rating of 2800 at age 18 and reached number one in the FIDE world rankings aged 19, becoming the youngest person ever to achieve those feats',
    'Initially, the “Queen” could only move one square at time diagonally',
    'There exists a hybrid sport of chess and boxing called chess boxing 🥊',
    'There are around 700 separate programming languages',
    'Fortran is the oldest commercial programming language, designed at IBM in the 1950s',
    'There are 3 very different types of Hackers, one being malicious, the other benevolent, and the last somewhere in between the two 🐱‍💻',
    'Amazingly, one of NASA’s flagship spacecraft, the Space Shuttle, runs on less code than many of today’s cellphones and other gadgets',
    'In the programming world, a bug is an error that causes a program to crash or behave in strange ways. The first computer "bug" was an actual real-life bug 🐜',
    'The first computer game was created in 1962 and the rest is history 🕹',
    'The first person in the world to carry the title of a coder was a woman named Ada Lovelace',
    'Computer programming is one of the fastest-growing careers',
    'An estimated 2.7 billion people played video games in 2020 alone. This increase is likely due to the global pandemic',
    'The ancient Egyptians were absolutely fascinated with cats, and it is through that most Ancient Egyptian families kept at least one as a pet 🐈',
    'You can actually download the entirety of Wikipedia and keep it on a USB drive 💽',
    'High heels were first designed for men 👠',
    '"I.e." and "e.g." are not the same thing',
    'The average person will spend six months of their life waiting for red lights to turn green 🚦',
    'There\'s a bridge exclusively for squirrels that cost $220K, but they aren\'t using it 🐿',
    'Marie Curie\'s notebooks are still radioactive ☢',
    'The Wow! signal was a strong narrowband radio signal detected on August 15, 1977, by the Ohio State University\'s Big Ear radio telescope in the United States, then used to support the search for extraterrestrial intelligence 👽',
    '👽 Wow! 6EQUJ5 Wow! 👽',
    'A sea lion once saved a man',
    'Pandas fake pregnancy for better care 🐼',
    'Crocodiles are one of the oldest living species, having survived for more than 200 million years 🐊',
    'A Canadian woman who lost her wedding ring while gardening found it 13 years later growing on a carrot 💍🥕',
    'Flipping a shark upside down renders it immobile for up to 15 minutes 🦈',
    'Tesla was briefly reduced to digging ditches for a living',
    'One July day, while tracking lightning storms, Tesla’s equipment picked up a series of beeps. After ruling out solar and terrestrial causes, he concluded that the signals must be from another planet',
    'Tesla was a pioneer in the discovery of radar technology, X-ray technology, remote control and the rotating magnetic field — the basis of most AC machinery.',
    'Nikola Tesla was born around midnight, between July 9 and July 10, 1856 during a fierce lightning storm. ⚡ This child will be a child of darkness, midwife said, to which his mother replied: “No. He will be a child of light.”',
    'Tesla had what’s known as a photographic memory. He was known to memorize books and images and stockpile visions for inventions in his head 📷',
    'Charles Babbage, an English mechanical engineer and polymath, originated the concept of a programmable computer 🖥',
    'Google has developed AI that can design chips for computers much faster than humans 🤖',
    'Deep Blue was the first AI robot, made in 1996. It was a chess-playing computer which won its first game against a World Champion on 10 February 1996',
    'One of the main - and most crucial - problems of AI is that even its creators can’t understand some of the decisions AI software makes and why 🤖',
    'Global spending on AI is predicted to double by 2024, which means it would amount to over $110 billion',
    'Most AI bots are female. Studies show that males and females are more attracted to a woman\'s voice',
    'Olaus Roemer was the first astronomer to measure the speed of light successfully. This happened in 1676 when he observed a time interval between successive eclipses of the moons of Jupiter 🔦',
    'Some theories, suggest that suitable geometries of spacetime or specific types of motion in space might allow time travel into the past and future if these geometries or motions were possible',
    'Time travel to the past is theoretically possible in certain general relativity spacetime geometries that permit traveling faster than the speed of light, such as cosmic strings, traversable wormholes, and Alcubierre drives',
    'When Neil Armstrong landed the lunar module, there were only 30 seconds of fuel left 🚀🌚',
    'An amazing woman called Katherine Johnson carried out the calculations that made the mission to the moon possible and got the astronauts home again',
    'Your cellphone is more powerful than Apollo 11’s computers 📱',
    '“The Eagle has landed,” is one of the most famous quotes in NASA history 🌑🦅',
    'Octopuses have three hearts 🐙',
    'At birth, a panda is smaller than a mouse and weighs about four ounces 🐼',
    'The bat is the only mammal that can fly 🦇',
    'Dogs sense of smell is at least 40x better than ours 🐶',
    'Your dog could be left or right-pawed 🐾',
    'Three dogs survived the Titanic sinking 🚢',
    'The African Hunting dog is the most successful mammalian hunter in the world 🐕',
    'A house cat is genetically 95.6% tiger 🐈🐅',
    'Cats can jump 5 times their height 🐈',
    'Between 2002 and 2012 the average lifespan of a cat increased by a year 😼',
    'Cats mark you as their territory by rubbing their faces and bodies against you, marking you with their scent 😼',
    'There are about 88 million pet cats in the United States, which makes them the most popular pet in the country',
    'There are over 20 lakes in the Sahara, most of which are saltwater lakes. Lake Chad is the only freshwater lake in the desert 🌵',
    'According to the Global Resource Information Database of the United Nations Environment Programme, Lake Chad shrank by as much as 95% from about 1963 to 1998',
    /*'XXXXXXXXXXXXXXXXXXXXXXxx',*/
    'Go is an abstract strategy board game for two players in which the aim is to surround more territory than the opponent <img src="assets/images/go-stone.png">',
    'Scotland wanted to replicate the Parthenon bigger and cheaper in 1826. It was never completed and is now nicknamed “Scotland’s Disgrace” <img src="assets/images/scotland.png">',
    'The unicorn is the national animal of Scotland <img src="assets/images/scotland.png">🦄',
    `Scotland has 421 words for “snow” <img src="assets/images/scotland.png">`,
    `Nxg7+ Kd8 Qf6+!! Nxf6 Be7# <img src="assets/images/emotes/emote-lit.png">`,
    `Qh6+!! Kxh6 (gxh6 Rxf7#) Rh8# <img src="assets/images/emotes/emote-magnus.png">`,
    `Bc5+ Kf1 Ng3+ Ke1 Bb4+ Kd1 Bb3+ Kc1 Ne2+ Kb1 Nc3+ Kc1 Rc2# <img src="assets/images/emotes/emote-fischer.jpg">`,
  ];

  fetchFacts() {
    return this.facts;
  }
}
